spring:
  config:
    import: env.properties
  application:
    name: social-media

  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: T:niuchaYL!2395

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
#  sql:
#    init:
#      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8000
